name: ci
on: [push, pull_request]
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm i
      - run: npm run lint:web
      - run: npm run typecheck:web
      - run: npm run test:web
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API Python deps
        run: python -m pip install --upgrade pip && pip install -r apps/api/requirements.txt
      - name: Dump OpenAPI (without server)
        run: npm run schema:dump:openapi
      - name: Compare OpenAPI snapshot (schemas only)
        continue-on-error: true
        run: |
          python - << 'PY'
          import json, sys
          from pathlib import Path
          cur = json.loads(Path('dist/openapi.json').read_text())
          base = json.loads(Path('docs/api/openapi.snapshot.json').read_text())
          def pick(x):
            return { 'openapi': x.get('openapi'), 'components': { 'schemas': x.get('components',{}).get('schemas',{}) } }
          if pick(cur) != pick(base):
            print('[openapi-diff] snapshot differs from generated spec. Update docs/api/openapi.snapshot.json in this PR.')
            # non-blocking: enforced by strict schema checks below
            sys.exit(0)
          print('[openapi-diff] no changes')
          PY
      - name: Validate Zod vs OpenAPI
        run: npm run schema:validate
      - name: Check OpenAPI components
        run: python3 apps/api/scripts/check_openapi.py
      - name: Check OpenAPI paths and responses
        run: python3 apps/api/scripts/check_openapi_paths.py
      - name: Evaluate API NFR (p95 & thresholds)
        run: python3 apps/api/scripts/evaluate_nfr.py
      - name: Check SLO thresholds
        run: npm run check:slo
        env:
          AUTOEDA_SLO_OUTPUT: reports/slo_report.json
      - name: Check RAG golden queries
        run: npm run check:rag
        env:
          AUTOEDA_RAG_OUTPUT: reports/rag_report.json
      - name: Merge QA reports
        run: npm run report:merge
        env:
          AUTOEDA_SLO_OUTPUT: reports/slo_report.json
          AUTOEDA_RAG_OUTPUT: reports/rag_report.json
          AUTOEDA_QA_SUMMARY: reports/quality_summary.json
      - name: Upload QA reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-reports
          path: reports
          if-no-files-found: ignore
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - run: npx playwright test --reporter=line,html
      - run: npm run build:web
